stages:
  - build
  - test
  - collect_artifacts

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .docker_ccache

build_wheel_debug_mac_10_15_python36:
  tags:
    - macos10.15
  only:
    variables:
      - $TC_HAS_MACOS_RUNNERS == "1"
  stage: build
  script:
    - export VIRTUALENV="/Library/Frameworks/Python.framework/Versions/3.6/bin/virtualenv"
    - source scripts/use_ccache.sh
    - bash -e scripts/make_wheel.sh --skip_test --skip_cpp_test --build_number=$CI_PIPELINE_ID --num_procs=4 --debug
  artifacts:
    expire_in: 1 day
    paths:
      - target/

build_wheel_mac_10_15_python36:
  tags:
    - macos10.15
  only:
    variables:
      - $TC_HAS_MACOS_RUNNERS == "1"
  stage: build
  script:
    - export VIRTUALENV="/Library/Frameworks/Python.framework/Versions/3.6/bin/virtualenv"
    - source scripts/use_ccache.sh
    - bash -e scripts/make_wheel.sh --skip_test --skip_cpp_test --build_number=$CI_PIPELINE_ID --num_procs=4
  artifacts:
    expire_in: 1 day
    paths:
      - target/

test_python_debug_mac_python36_10_14:
  tags:
    - macos10.14
  only:
    variables:
      - $TC_HAS_MACOS_RUNNERS == "1"
  stage: test
  dependencies:
    - build_wheel_debug_mac_10_15_python36
  script:
    - export VIRTUALENV="/Library/Frameworks/Python.framework/Versions/3.6/bin/virtualenv"
    - export TC_ENABLE_S3_TESTS=1
    - bash -e scripts/test_wheel.sh
  artifacts:
    when: always
    expire_in: 2 weeks
    paths:
      - pytest.*

test_python_debug_mac_python36_10_14_1:
  tags:
    - macos10.14
  only:
    variables:
      - $TC_HAS_MACOS_RUNNERS == "1"
  stage: test
  dependencies:
    - build_wheel_debug_mac_10_15_python36
  script:
    - export VIRTUALENV="/Library/Frameworks/Python.framework/Versions/3.6/bin/virtualenv"
    - export TC_ENABLE_S3_TESTS=1
    - bash -e scripts/test_wheel.sh
  artifacts:
    when: always
    expire_in: 2 weeks
    paths:
      - pytest.*

test_python_mac_python36_10_14:
  tags:
    - macos10.14
  only:
    variables:
      - $TC_HAS_MACOS_RUNNERS == "1"
  stage: test
  dependencies:
    - build_wheel_mac_10_15_python36
  script:
    - export VIRTUALENV="/Library/Frameworks/Python.framework/Versions/3.6/bin/virtualenv"
    - export TC_ENABLE_S3_TESTS=1
    - bash -e scripts/test_wheel.sh
  artifacts:
    when: always
    expire_in: 2 weeks
    paths:
      - pytest.*

test_python_mac_python36_10_14_1:
  tags:
    - macos10.14
  only:
    variables:
      - $TC_HAS_MACOS_RUNNERS == "1"
  stage: test
  dependencies:
    - build_wheel_mac_10_15_python36
  script:
    - export VIRTUALENV="/Library/Frameworks/Python.framework/Versions/3.6/bin/virtualenv"
    - export TC_ENABLE_S3_TESTS=1
    - bash -e scripts/test_wheel.sh
  artifacts:
    when: always
    expire_in: 2 weeks
    paths:
      - pytest.*


collect_artifacts:
  tags:
    - docker
  services:
    - docker:18.09-dind
  image: alpine:latest
  stage: collect_artifacts
  dependencies:
    - build_wheel_mac_10_15_python36
    - build_wheel_debug_mac_10_15_python36
  script:
    - find release/src/deployment/ -name '*.dylib' -exec mv {} target/ \;
    - rmdir -p release || find release
  artifacts:
    expire_in: 2 weeks
    paths:
      - target/
